### ISSUE TITLE
Kamoso: clicking on bottom left menu button sometimes freezes or crashes kamoso

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#40]

**Comment by star-buck** [comment]
still remains an issue when kwin uses gles, so we either find a fix or we remove kamoso knowing this will look like broken software for users...

**Comment by aleixpol** [comment]
I've been tinkering with it a bit more, this seems to fix the issue for me completely.
https://commits.kde.org/kamoso/6fd7caa6da736a7f465cee8ed01cb433e5257776

**Comment by star-buck** [comment]
@aleixpol @bhush9 : is the fix supposed to be in latest img?

**Comment by bhush9** [comment]
Yeah, this change is already in new image : https://build.neon.kde.org/job/xenial_unstable_kde-extras_kamoso/changes (it got in package of march 3)

**Comment by star-buck** [comment]
then sadly its not fixed here, still pulling the handle freezes+crashes kamoso

**Comment by star-buck** [comment]
to reproduce:
take a snapshot, then try open the left sidebar freezes

**Comment by aleixpol** [comment]
It looks to me like it's a different issue, I have to open and close the sidebar repeatedly. The method suggested by star-buck doesn't trigger a crash.

Here's a bit of the infinite recursion I'm hitting, any pointers will be welcome!
```
#523 0x0000007fb505765c in _mali_convert_intrinsics_8x8_tile () from /usr/lib/aarch64-linux-gnu/mali-egl/libGLESv2.so.2
#524 0x0000007fb505765c in _mali_convert_intrinsics_8x8_tile () from /usr/lib/aarch64-linux-gnu/mali-egl/libGLESv2.so.2
#525 0x0000007fb505765c in _mali_convert_intrinsics_8x8_tile () from /usr/lib/aarch64-linux-gnu/mali-egl/libGLESv2.so.2
#526 0x0000007fb505765c in _mali_convert_intrinsics_8x8_tile () from /usr/lib/aarch64-linux-gnu/mali-egl/libGLESv2.so.2
#527 0x0000007fb505765c in _mali_convert_intrinsics_8x8_tile () from /usr/lib/aarch64-linux-gnu/mali-egl/libGLESv2.so.2
#528 0x0000007fb505765c in _mali_convert_intrinsics_8x8_tile () from /usr/lib/aarch64-linux-gnu/mali-egl/libGLESv2.so.2
#529 0x0000007fb505765c in _mali_convert_intrinsics_8x8_tile () from /usr/lib/aarch64-linux-gnu/mali-egl/libGLESv2.so.2
#530 0x0000007fb505765c in _mali_convert_intrinsics_8x8_tile () from /usr/lib/aarch64-linux-gnu/mali-egl/libGLESv2.so.2
```

**Comment by shadeslayer** [comment]
Backtrace indicates it's in the proprietary part of the stack :(
