### ISSUE TITLE
Tips from the Pinebook community to improve overall experience

### ISSUE THREAD

**Issue by shadeslayer** [blue-systems/neon-pinebook#58]
I was pointed to this https://forum.pine64.org/showthread.php?tid=4982 recently as something we should investigate and ship on the Pinebook.

I can't really advocate shipping random python and bash scripts, but perhaps they can be cleaned up and improved and made into proper configs for KDE that can be shipped.

**Comment by sebasje** [comment]
I've gone through the suggestions one by one. Some are hardware hacks (add a switch to enable debugging over headphone jack, add a wooden plate to improve the touchpad), some are already squarely on our radar (various rendering and video playback improvements), but there are some configuration options and improvements hidden in there.  I've filed separate issues for these, making this more well-defined a task, so we can tackle them one by one:
See 
* https://github.com/blue-systems/neon-pinebook-remix/issues/67
* https://github.com/blue-systems/neon-pinebook-remix/issues/66
* https://github.com/blue-systems/neon-pinebook-remix/issues/65

I'll close this issue, as we're tracking the useful bits in the above ones now.
