### ISSUE TITLE
Wifi: we need to ship improved icon, as current is almost non-visible

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#61]
![screenshot_20180210_120911](https://user-images.githubusercontent.com/840070/36062207-8b43f00e-0e67-11e8-8a62-6c9467e46e4a.png)

**Comment by bhush9** [comment]
https://phabricator.kde.org/D10243 

Revision is pending review.

**Comment by sebasje** [comment]
The suggested improvement doesn't really address the issue, it makes a few other states more visible. The plan right now is to make the disconnected icon red.

**Comment by star-buck** [comment]
one week later, can a decision been made, its not that hard to mitigate this obvious bad state, even if refined later again...

**Comment by sebasje** [comment]
We want to make the icon red instead of translucent, this needs a designer to change it. I've asked Andreas to make that change.

**Comment by adriaandegroot** [comment]
I posted some photo's to the telegram channel -- with the pinebook on my lap, and wifi disconnected (like it would be at first boot), the wifi icon is leftmost in the systray, so it's almost invisible from the viewing angle of a laptop user. The greys are totally washed out, as is the yellow ? (gosh, I never looked at it that closely before) and the little black tick-mark? It could be a speck of dirt on the screen. Only by looking directly at the icon does it become somewhat visible.

This is an effect of the not-so-hot TN panel in the pinebook, which affects desktops and IPS-panel laptops much less.

**Comment by llelectronics** [comment]
Did that "change the icon to red" ever land somewhere? It isn't hard to change the icon to red which would make it visible. Though if VDG is involved it might end up in discussions and such :P

**Comment by notmart** [comment]
if nothing moved yet, i may just do it, or take my vdg whip and make them in line (getting pretty good at yelling at them in a non confrontational way lately)

**Comment by sebasje** [comment]
The make-it-red didn't land, while it seems a rather easy solution here. If notmart (probably our best bet at whipping or inkscaping himself) could take a look, that would be _awesome_.

**Comment by llelectronics** [comment]
Ok something really strange this file has already a red color: /usr/share/icons/breeze-dark/status/22/network-wireless-disconnected.svg . At least on my system. Though it might be that plasma-nm is not using that icon but some other one.

**Comment by notmart** [comment]
that's an idea i had:
![spectacle z25324](https://user-images.githubusercontent.com/4526371/37487050-a98fe034-2890-11e8-9f83-5cc751dc7a2b.png)
(rationale: most higs recommends against using only color to convey information as would break for color blind people)

**Comment by notmart** [comment]
> Ok something really strange this file has already a red colorOk something really strange this file has already a red color

that's normal, it needs to be done in more than one place, in the plasma theme as well, i can either put the one of breeze tough would prefer a non color - only version

**Comment by notmart** [comment]
new icons pushed in plasma-framework, to be tested in next image

**Comment by bhush9** [comment]
http://weegie.edinburghlinux.co.uk/~neon/images/pinebook-remix/20180319-1110/ fix is in.

**Comment by star-buck** [comment]
its not that nice solution (the red strike when not connected), but it got more visible, yes.
