### ISSUE TITLE
boot: before sddm shows up, terminal login prompt is visible for about 5 seconds (a bit confusing)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#64]
maybe there is a chance to still show plymouth neon logo or remove the wait before sddm shows

**Comment by bhush9** [comment]
As a side effect of the fix for #72, we realized that we were shipping the live-config file which caused tty to show up briefly.. I've killed it and it should be fixed in https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180504-1120/ already.

**Comment by bhush9** [comment]
Just as reminder, this bug is not present in latest image : https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180601-1242/
