### ISSUE TITLE
Switch audio output to headphone only when it's plugged in

### ISSUE THREAD

**Issue by sebasje** [blue-systems/neon-pinebook#65]
When a headphone is plugged in, the user expects the audio output to go only there, so it should be switched from main speakers to headphones. The original thread talks about alsa, but I believe that this is actually a pulseaudio configuration thing.

from https://forum.pine64.org/showthread.php?tid=4982

**Comment by star-buck** [comment]
uups, just saw this existed... well now it is bumped :)
