### ISSUE TITLE
Disable trackpad while typing / "palm rejection"

### ISSUE THREAD

**Issue by sebasje** [blue-systems/neon-pinebook#66]
This is a config option in Plasma's touchpad KCM, but for synaptics there's also a driver config which enables palm detection. The task here is to:

* Check if the touchpad driver of the pinebook has such an option, if so, make sure it's enabled
* if not: evaluate whether we want to switch the Plasma option on by default (I personally never needed it and found it somewhat annoying, this may boil down to a matter crappy touchpad hardware / fat fingering and taste

from: https://forum.pine64.org/showthread.php?tid=4916&highlight=proof+of+concept (note that we definitely do not want to use that script as is)

**Comment by kbroulik** [comment]
> I personally never needed it and found it somewhat annoying

Yup, it took me ages to find out on my laptop that it was this feature that had my touchpad "randomly" not work immediately.

**Comment by adriaandegroot** [comment]
This has been added as a script in the latest release. It disables the touchpad while typing.
