### ISSUE TITLE
Konsole redraw glitch

### ISSUE THREAD

**Issue by adriaandegroot** [blue-systems/neon-pinebook#69]
(This might be covered entirely by #68)

On starting konsole, sometimes there are short white stripes in the window. They go away after almost any repaint event. While typing, the glitches sometimes reappear.

![konsole](https://user-images.githubusercontent.com/19431457/37459138-8f22fccc-281d-11e8-8c00-474dac497f38.png)

**Comment by adriaandegroot** [comment]
(it's the white horizontal line, about vertically centered and just to the right of center, in the konsole window)

**Comment by star-buck** [comment]
This is likely the blue/white lines glitch that d_ed is working to solve.

**Comment by davidedmundson** [comment]
Yep. Will close this as there's notes already on that kwin with GLES thread.
