### ISSUE TITLE
LibreOffice: white menu fonts and splash glitch

### ISSUE THREAD

**Issue by adriaandegroot** [blue-systems/neon-pinebook#71]
- libreoffice
-- [ ] menu fonts are white
-- [ ] washed-out splash screen

Starting LibreOffice produces a weird splash screen, which is washed-out. In this screenshot, red arrow (1) points at the LO splash / banner, which is washed-out and mostly transparent, in front of KInfoCenter (2).

![lo1](https://user-images.githubusercontent.com/19431457/37460198-e84a5266-2820-11e8-9644-4e2dac872937.png)

Here is the same situation, on a KDE Slimbook (x86_64, skylake graphics), (1) points to the splash / banner, (2) points to the KInfocenter application behind the splash.

![lo1a](https://user-images.githubusercontent.com/19431457/37460207-ef7aaba8-2820-11e8-97e6-4b36acb82c53.png)

Once started, LO looks normal (er, for an application I start maybe twice a year) to me.

**Comment by adriaandegroot** [comment]
![lo2](https://user-images.githubusercontent.com/19431457/37460304-38163396-2821-11e8-89ee-f89e57e0971a.png)

Here is a normal-looking (?) LO window on the pinebook.

**Comment by subdiff** [comment]
This is a similar problem as to how it was for the application windows of Writer and so on before we installed the suitable libreoffice-gtk3 package.

I assume the splash screen just does not already use this backend package to render. Not sure how we can force it to do this.

A workaround is to deactivate the splash altogether by launching LibreOffice with the `--nologo` flag or change the `Logo` value from 1 to 0 in `/etc/libreoffice/sofficerc`.

**Comment by star-buck** [comment]
latest img: I am getting the white fonts when opening a menu again

**Comment by star-buck** [comment]
update: after another restart, the fonts are normal again... looking into if I am able to reproduce this somehow.

**Comment by bhush9** [comment]
Just as note: I can't reproduce the white fonts in newer bionic images. Can someone confirm?

**Comment by star-buck** [comment]
works here
