### ISSUE TITLE
graphics: 0404-1031 glitches

### ISSUE THREAD

**Issue by adriaandegroot** [blue-systems/neon-pinebook#73]
- konsole text cursor quickly gets garbled / stripes through it, generally fixed by forcing a switch in focus to a different window

**Comment by bhush9** [comment]
I wonder if this is : https://github.com/blue-systems/neon-pinebook-remix/issues/68 ?

**Comment by davidedmundson** [comment]
It is.
Goes away when we go back to using KWIN_COMPOSE=X.
