### ISSUE TITLE
calamares: 0404-1031 bad configuration

### ISSUE THREAD

**Issue by adriaandegroot** [blue-systems/neon-pinebook#74]
You can't run the installer because the settings.conf refers to Calamares modules which are not installed.

Quick fix: `sudo vi /etc/calamares/settings.conf`
Remove the lines 31, 32 `- deferred_remove` and `- deferred_resize`

However, the "live" user isn't removed, and the SD card isn't resized (because those modules have been removed). Needs a real fix.

**Comment by bhush9** [comment]
> Calamares modules which are not installed.

When were this modules removed?  possibly this will also affect xenial image.

**Comment by adriaandegroot** [comment]
The modules were not removed; but they weren't found any more by the default search mechanism. There is a `/usr/lib/calamares/modules/` on the image -- which looks like it comes from Calamares itself, and Calamares was built with a non-gnu-tripletted libdir (this might be a change in master, since I have been messing with where libraries go). So Calamares looks there. There is *also* a `/usr/lib/aarch64-linux-gnu/calamares/modules/` which is where the Neon pinebook package puts its configurations for extra modules. Calamares doesn't look there by default (why should it? it looks in libdir).

As a bit of a hack I have added the tripletted libdir in to the search path, that does the trick for me.

Medium term:
 - fix build of Calamares to use tripletted libdir again, or,
 - move the module definitions into un-tripletted libdir, or,
 - replace the modules with shellprocess, which is the bestest option.

**Comment by bhush9** [comment]
Marking this as ready for QA, as https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180504-1120/ have this fixed.
