### ISSUE TITLE
after installation & reboot, folderview doesnt come up

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#79]
it results in a black area space instead of folderview loading.
The panel and menus/systray load fine.

**Comment by star-buck** [comment]
comes up second time, but wallpaper dialog fails:
![screenshot_20180601_180034](https://user-images.githubusercontent.com/840070/40851088-942f3140-65c6-11e8-818b-183141dfd9cb.png)

**Comment by bhush9** [comment]
Wallpaper dilaog should be fixed in latest image (it's same kirigiami issue affecting discover etc)
