### ISSUE TITLE
kamoso: doesnt start

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#80]

**Comment by bhush9** [comment]
(Same issue as #81) Needs packaging.

**Comment by bhush9** [comment]
Fixed in https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180601-1242/

**Comment by bhush9** [comment]
Can't reproduce in : https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180620-0516/

**Comment by bhush9** [comment]
It starts properly in : http://files.kde.mirror.pangea.pub/neon/images/pinebook-remix-nonfree/neon-pinebook-remix-useredition-20180730-1137-arm64.img.gz
