### ISSUE TITLE
prepare RC img based on user stable, announce on pine forums to get testing feedback

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#86]

**Comment by bhush9** [comment]
We now have a image based on user-edition : http://files.kde.mirror.pangea.pub/neon/images/pinebook-remix-nonfree/neon-pinebook-remix-useredition-20180730-1137-arm64.img.gz

(It is not hosted on kde.org server due to publishing script breaking, will be fixed in next image)

**Comment by bhush9** [comment]
The images are now at : https://files.kde.org/neon/images/pinebook-remix-nonfree/useredition/

**Comment by star-buck** [comment]
done and closed
