### ISSUE TITLE
cala: doesnt remove itself fully (or maybe the icon left is intentional)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#91]
after install+reboot (not sure what RELE.. really means, maybe its in purpose?):
![screenshot_20180128_170216](https://user-images.githubusercontent.com/840070/43712302-f134a266-9975-11e8-8335-89d6657b3662.png)

**Comment by bhush9** [comment]
RELE.. is Release... but yes, icon seems to be there for some reason, will investigate.

**Comment by bhush9** [comment]
Ah, this is ubiquity actually.. which comes from user edition.. Will fix.

**Comment by bhush9** [comment]
This is fixed in the : https://files.kde.org/neon/images/pinebook-remix-nonfree/useredition/20180807-0602/
