### ISSUE TITLE
add frei0r-plugins for kamoso fx

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook#93]

**Comment by aleixpol** [comment]
It needs some runtime dependencies. After running this command everything works:
`sudo apt install frei0r-plugins gstreamer-plugins-bad`

**Comment by star-buck** [comment]
@bhush9 : gstreamer-plugins-bad doesnt exist, but adding frei0r-plugins fixes the issue.

**Comment by bhush9** [comment]
Added to list, new image needs rebuilding.

**Comment by star-buck** [comment]
works
